FROM nginx

COPY ./docker-entry.sh /docker-entrypoint.s
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./10-listen-on-ipv6-by-default.sh /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
COPY ./20-envsubst-on-templates.sh /docker-entrypoint.d/20-envsubst-on-templates.s
